params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: "<twitter>"
            url: "<link>"
        - name: "<github>"
            url: "<link2>"